### ISSUE TITLE
Support Laravel 5.x

### ISSUE THREAD

**Issue by Schnoop** [aaronlord/laroute#12]
Will there be support for Laravel 5.x?

**Comment by Kussie** [comment]
Any update on L5 support?

**Comment by aaronlord** [comment]
Been waiting for a date closer to release since there were a bunch of changes taking.

So, very soon.

**Comment by Kussie** [comment]
It's pretty stable right now, no more code changes are being made to it.  Maybe a new Laravel 5 branch or something.  Would be nice so we could start getting ready to migrate our app to laravel 5.

**Comment by Kussie** [comment]
It's officially released now :)

**Comment by aaronlord** [comment]
Aye! I'm on it

**Comment by xeno010** [comment]
see here #15 Full Laravel 5 support

**Comment by aaronlord** [comment]
Merged, thanks @xeno010
