### ISSUE TITLE
Wrong Urls when in app in subdir

### ISSUE THREAD

**Issue by yadue** [aaronlord/laroute#14]
If app sits in subdirectory ie: domain.com/app/api/get-users (where  /app/ is the main public dir then routes are generated incorrectly pointing to domain.com/api/get-users. Generator does not look up for routes in subdirectories like usual laravel router.

**Comment by aaronlord** [comment]
It took me a while to figure out what you're asking, but I get what you mean now :)

You've renamed `/public` to `/app`, and, `domain.com` maps to the `/`, not `/app`.

Thinking how to implement.

**Comment by xeno010** [comment]
@yadue 

Set the "absolute" option to true and set your correct application url in config/app.php. 
Only for laroute >= 2.0.

**Comment by aswi-pro** [comment]
Just provide a "prefix" option in configurations.
