### ISSUE TITLE
Don't force user to pass an object

### ISSUE THREAD

**Issue by Anahkiasen** [aaronlord/laroute#18]
Currently Laroute behaves the same way as the UrlGenerator, but there is one caveat. While in PHP you don't have to specify the name of the arguments, in Laroute you do:

```php
URL::route('users.show', 3); // foo.com/users/3
```

```js
laroute.route('users.show', {user: 3}); // foo.com/users/3
laroute.route('users.show', 3); // foo.com/users/{users}?3
```

Could this difference of behavior be fixed?

**Comment by aaronlord** [comment]
It should be possible by reading `arguments`. Feel free to give it a shot and send a PR.

**Comment by Anahkiasen** [comment]
I would but you should add a CONTRIBUTING.md cause right now I'm kinda confused as to which file I should edit. There's a minified version in `public/js` but there's also one in `src/templates`. There is a Grunt task available but it seems outdated as it still refers to the old paths. When I modify `src/templates/laroute.js` the change don't see to show up in the tests, which file should I edit?

**Comment by aaronlord** [comment]
Edit `src/templates/laroute.js`, then run the grunt task to minify it.

It's messy. I get it. I've started re-writing the whole thing, but work keeps getting in the way ):

**Comment by Anahkiasen** [comment]
Hm that's incorrect, the grunt task creates `src/templates/laroute.min.js` but the Karma tests use `public/js/laroute.js` which contains some dummy routes, so there's not really any way to update the Laroute version used by Karma besides editing `public/js/laroute.js` :/ Will see if I find a way

**Comment by aaronlord** [comment]
It's not incorrect. The grunt task does minify `src/templates/laroute.js` to `src/templates/laroute.min.js`.

Generating laroute with artisan uses the contents of `src/templates/laroute.min.js` (by default), replaces the placeholders (e.g. `$ROUTES`) with your data, and spits the file out into `public/js/laroute.js` (by default).

Karma tests the output. So you need to install laroute within a Laravel install, change the output/input files as necessary, use artisan to generate the output file and then run Karma.
