### ISSUE TITLE
The use of preg_replace to generate the .js file might leak special characters in Javascript

### ISSUE THREAD

**Issue by Recon** [aaronlord/laroute#25]
Let's say we have this route

```php
Route::get('/something', [
    'laroute' => true,
    'as' => 'something',

     // Note the lowercase u from user@..., typically this value 
     // starts with an uppercase letter and the following problem won't apply
    'uses' => 'user@someMethod'
]);
```

At [some point](https://github.com/aaronlord/laroute/blob/a3c7d2c/src/Routes/Collection.php#L36) the value of `uses` from above will end up in an array

```php
array:2 [
    //...
    "action" => "App\Http\Controllers\user@someMethod"
    //...
]
```

 [Later on](https://github.com/aaronlord/laroute/blob/a3c7d2c/src/Console/Commands/LarouteGeneratorCommand.php#L104) that piece will end up being `json_encode`ed, which will generate a string containing 

```
... App\\Http\\Controllers\\user@someMethod ...
```

When converted to json, the backslashes are escaped, as expected.

Ultimately, this json will [end up being replaced](https://github.com/aaronlord/laroute/blob/a3c7d2c/src/Compilers/TemplateCompiler.php#L23) in the template via `preg_replace`, However, that double backslash `\\` will end up being a single `\` backslash afterwards

> To use backslash in replacement, it must be doubled ("\\\\\\\\" PHP string). [link](http://php.net/manual/en/function.preg-replace.php)

Thus, in the file generated from [routes.js template](https://github.com/aaronlord/laroute/blob/a3c7d2c/src/templates/laroute.js#L9), that json will look like

```
... App\Http\Controllers\user@someMethod ...
```
In this case, the `\u` will be interpreted by Javascript as the start of a unicode escape sequence, and since it isn't followed by a hex number, it will trigger an error: 

```
SyntaxError: malformed Unicode character escape sequence
```

Similar stuff might also happen with `\b, \f, \n, \r, \t, \v`

If it was up to me I would simply use a `str_ireplace` instead, in [TemplateCompiler](https://github.com/aaronlord/laroute/blob/a3c7d2c/src/Compilers/TemplateCompiler.php#L23), which would preserve the escaped backslashes until the end, but I am not sure if I'm missing some other reason why `preg_replace` was used.

**Comment by aaronlord** [comment]
Thanks for pointing this out, however I can't imagine this causing any real-world problems (as you said, the class should be studly case).

I can't remember off the top of my head why `preg_replace` was used over `str_ireplace`. I'm trying to find time to work on the next version of laroute, so I'll keep this in mind. At the very least, there might be a performance gain to be had.
