### ISSUE TITLE
Laravel 5.3 support?

### ISSUE THREAD

**Issue by mits87** [aaronlord/laroute#40]
Hi, 

is it possible support laravel 5.3?

Best Regards
Peter

**Comment by reecss** [comment]
Support for Laravel 5.3 was added in v2.3.0

It looks like composer is targeting the 5.2 tag on Packagist by default though, so you'll have to explicitly require v2.3 in your composer.json

**Comment by aaronlord** [comment]
Which is very annoying. Must delete the damn thing three times a week.
