### ISSUE TITLE
How to use it with dingo api routes

### ISSUE THREAD

**Issue by rohitkhatri** [aaronlord/laroute#46]
Is there a way to include only dingo api routes?

**Comment by aaronlord** [comment]
huh?

**Comment by rohitkhatri** [comment]
@aaronlord when I generate js from this library, It doesn't contain dingo api routes.

**Comment by aaronlord** [comment]
Are you referring to this? https://github.com/dingo/api

**Comment by rohitkhatri** [comment]
Yes.

**Comment by aaronlord** [comment]
Uhm. I've never heard of it before, so unfortunately my answer is I don't know.

Based on a quick glance, it looks like it would require me investing a chunk of time to fit this specific use case.

Feel free to prove me wrong and submit a PR or reply in this thread if you figure out a way to implement that isn't specific to dingo.
