### ISSUE TITLE
Template laroute.js not found when executing laroute:generate from outside the base application install folder

### ISSUE THREAD

**Issue by percymamedy** [aaronlord/laroute#80]
I am using deployer to deploy my site to production. One of the tasks I defined was as follows

```php
task('artisan:laroute:generate', function () {
    run('{{bin/php}} {{release_path}}/artisan laroute:generate');
});
```

However I get the following error when deploying:

```bash
Executing task artisan:laroute:generate
[mysite.com] > /usr/local/bin/php ~/releases/12/artisan laroute:generate
[mysite.com] < stdin: is not a tty
[mysite.com] < File does not exist at path vendor/lord/laroute/src/templates/laroute.js
```

When running the command manually on the server it works.

Any ideas ?

**Comment by martdegraaf** [comment]
Did you do it after the composer install?

**Comment by percymamedy** [comment]
I actually found the issue was that when executing artisan from outside the base install folder the path of the template files could not be resolved.

For example if my application was installed in ```/var/www``` and I was in ```/var``` trying to execute php artisan like so :

```bash
$ /var: php www/artisan laroute:generate 
```

The path defined in config ```laroute.php``` broke down and could not be resolved since it was looking in the ```/var``` folder.

This PR should get it fixed : https://github.com/aaronlord/laroute/pull/81
